Us10 reset
ekat-br/roomcheck pull request #20
Opened 2023-07-31 10:44 UTC by ekat-br

This is the PR for [US10](https://github.com/ekat-br/roomcheck/issues/16). Thanks in advance for reviewing my code.

2023-07-31 13:28 UTC, Roland-Hufnagel requested changes
Hi Katja, your solution will not work in reality. The reason is that vercel provides serverless functions. This means your code is only executed, when it is requested by a browser. After the response is sent, the server will go to sleep and not execute your code anymore. Therefor the setInterval() will not be executed every minute. To solve this problem you have to create a ``cronjob``. 

A cronjob is a scheduled request to an specified URL. (it's exactly the same thing, as if you call that URL in your browser at 10:50 and 23:50 each day). You can define which URL to call and when (e.g. at 10:50 and 23:50). For the URL you define an API route (e.g. 'pages/api/admin/index.js) where you write a handler function that resets the room states. A cronjob does exactly the same as y 

You can define a cronjob on vercel (https://vercel.com/guides/how-to-setup-cron-jobs-on-vercel), 2 jobs a day are included in the free plan, or at any other supplier (some are mentioned on the link above). There are several providers for cronjobs in the www, some for free and some to be paid.

2023-07-31 13:28 UTC, Roland-Hufnagel commented on package.json
> +    "node-fetch": "^3.3.2",
??? What is the need for that?

2023-07-31 13:28 UTC, Roland-Hufnagel commented on pages/api/rooms/index.js
> +}, 60000);
I think this won't work in reality. Since vercel provides serverless-functions, this setInterval will be killed after some seconds and will not be executed every minute.

2023-07-31 13:28 UTC, Roland-Hufnagel commented on pages/api/rooms/index.js
> +    await Room.updateMany({}, { status: "Keine Angabe" });
you cannot call the DB Without a connection.

2023-07-31 13:32 UTC, ekat-br commented on package.json
> +    "node-fetch": "^3.3.2",
thats nonsense, will delete it

2023-07-31 13:35 UTC, ekat-br commented on pages/api/rooms/index.js
> +}, 60000);
It worked, that's why I posted the code. But if you say, it would be better to use cronjobs, I will think about implementing this.

2023-07-31 14:31 UTC, ekat-br commented
I have implemented the suggested changes. 
Additionally I have created two cron-obs with [cron.jobs.org](https://cron-job.org/de/).
![Bildschirmfoto 2023-07-31 um 16 30 57](https://github.com/ekat-br/roomcheck/assets/64787391/38fc0afa-1a9e-484d-a722-a712910a3b39)

![Bildschirmfoto 2023-07-31 um 16 29 56](https://github.com/ekat-br/roomcheck/assets/64787391/5106bb31-ed56-4a7e-bf6c-e758ead6c5c1)

After this code review, I will merge this code and then test the cronjobs in detail.

2023-08-01 06:44 UTC, MonaHer reviewed
Hi Katja, looks good to me! 😊 I really like this US, I think it's a very cool feature! ✨ Fingers crossed that it will work with the cronjobs 🤞

2023-08-01 10:02 UTC, ekat-br commented
This user story must be merged now to fully check the functionality.

2023-08-01 10:02 UTC, merged